In [5]:
import numpy as np 

In [7]:
np.add.accumulate([2, 3, 5]) #Возвращает совокупную сумму элементов по заданной оси

array([ 2,  5, 10])

In [8]:
np.multiply.accumulate([2, 3, 5])

array([ 2,  6, 30])

In [9]:
I = np.eye(2)

In [10]:
I

array([[1., 0.],
       [0., 1.]])

In [11]:
np.add.accumulate(I, 0)

array([[1., 0.],
       [1., 1.]])

In [12]:
np.add.accumulate(I)

array([[1., 0.],
       [1., 1.]])

In [13]:
np.add.accumulate(I, 1)

array([[1., 1.],
       [0., 1.]])